//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MaNV { get; set; }
        public string MaCV { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<bool> CheckNgay { get; set; }
    }
}
