//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_QLCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHAMCONG
    {
        public string MaNV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<int> NgDilam { get; set; }
        public Nullable<int> SoNgNghiPhep { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
        public CHAMCONG()
        {
            NgDilam = 0;
            SoNgNghiPhep = 1;
        }
        public CHAMCONG(string maNV, int thang, int nam)
        {
            MaNV = maNV;
            Thang = thang;
            Nam = nam;
        }
        public CHAMCONG(string maNV, int thang, int nam, int? ngDilam, int? soNgNghiPhep)
        {
            MaNV = maNV;
            Thang = thang;
            Nam = nam;
            NgDilam = ngDilam;
            SoNgNghiPhep = soNgNghiPhep;
        }
    }
}
