//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_QLCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHECKIN_OUT
    {
        public string MaNV { get; set; }
        public System.DateTime Ngay { get; set; }
        public Nullable<bool> CheckInSang { get; set; }
        public Nullable<bool> CheckOutChieu { get; set; }
        public string LyDoNghi { get; set; }
    
        public virtual NHANSU NHANSU { get; set; }
    }
}
