//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class DUAN
    {
        public string MaDA { get; set; }
        public string TenDA { get; set; }
        public string MaPB { get; set; }
        public Nullable<decimal> VonDH { get; set; }
        public string TruongDA { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public string TrangThai { get; set; }
        public DUAN(string mada, string tenda, string mapb, string truongda, DateTime ngaybd, DateTime ngaykt, string trangthai)
        {
            MaDA = mada;
            TenDA = tenda;
            MaPB = mapb;
            TruongDA = truongda;
            NgayBD = ngaybd;
            NgayKT = ngaykt;
            TrangThai = trangthai;
        }
    }
}
