//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_QLCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class NHANSU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public NHANSU()
        {
            this.CHAMCONGs = new HashSet<CHAMCONG>();
            this.CHECKIN_OUT = new HashSet<CHECKIN_OUT>();
            this.DUANs = new HashSet<DUAN>();
            this.NGHIPHEPs = new HashSet<NGHIPHEP>();
            this.PHANCONGDUANs = new HashSet<PHANCONGDUAN>();
            this.PHONGBANs = new HashSet<PHONGBAN>();
            this.TIENLUONGs = new HashSet<TIENLUONG>();
        }
    
        public string MaNV { get; set; }
        public string HovaTendem { get; set; }
        public string Ten { get; set; }
        public Nullable<System.DateTime> NgaySinh { get; set; }
        public string DiaChi { get; set; }
        public string CCCD { get; set; }
        public string MaPB { get; set; }
        public string GioiTinh { get; set; }
        public string SDT { get; set; }
        public string Email { get; set; }
        public string MaCV { get; set; }
        public string TrinhDo { get; set; }
        public NHANSU(string maNV, string hovaTendem, string ten, DateTime? ngaySinh, string diaChi, string cCCD, string maPB, string gioiTinh, string sDT, string email, string maCV, string trinhDo)
        {
            MaNV = maNV;
            HovaTendem = hovaTendem;
            Ten = ten;
            NgaySinh = ngaySinh;
            DiaChi = diaChi;
            CCCD = cCCD;
            MaPB = maPB;
            GioiTinh = gioiTinh;
            SDT = sDT;
            Email = email;
            MaCV = maCV;
            TrinhDo = trinhDo;
        }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHAMCONG> CHAMCONGs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CHECKIN_OUT> CHECKIN_OUT { get; set; }
        public virtual CHUCVU CHUCVU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DUAN> DUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<NGHIPHEP> NGHIPHEPs { get; set; }
        public virtual PHONGBAN PHONGBAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHANCONGDUAN> PHANCONGDUANs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PHONGBAN> PHONGBANs { get; set; }
        public virtual TAIKHOAN TAIKHOAN { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TIENLUONG> TIENLUONGs { get; set; }
        public virtual TRANGTHAINHANVIEN TRANGTHAINHANVIEN { get; set; }
    }
}
