//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_QLCongTy
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONGDUAN
    {
        public string MaDA { get; set; }
        public string MaNV { get; set; }
        public string CongViec { get; set; }
        public System.DateTime NgayBD { get; set; }
        public System.DateTime NgayKT { get; set; }
        public Nullable<int> TienDo { get; set; }
    
        public virtual DUAN DUAN { get; set; }
        public virtual NHANSU NHANSU { get; set; }
        public PHANCONGDUAN(string maDA, string maNV, string congViec, DateTime ngayBD, DateTime ngayKT, int tienDo)
        {
            MaDA = maDA;
            MaNV = maNV;
            CongViec = congViec;
            NgayBD = ngayBD;
            NgayKT = ngayKT;
            TienDo = tienDo;
        }
        public PHANCONGDUAN()
        {

        }
    }
}
