//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHANCONGDUAN
    {
        public string MaDA { get; set; }
        public string MaNV { get; set; }
        public string CongViec { get; set; }
        public Nullable<System.DateTime> NgayBD { get; set; }
        public Nullable<System.DateTime> NgayKT { get; set; }
        public Nullable<int> TienDo { get; set; }
        public PHANCONGDUAN(string mada, string manv, string congviec, DateTime ngaybd, DateTime ngaykt)
        {
            MaDA = mada;
            MaNV = manv;
            CongViec = congviec;
            NgayBD = ngaybd;
            NgayKT = ngaykt;
        }
    }
}
