//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class PHONGBAN
    {
        public string MaPB { get; set; }
        public string TenPB { get; set; }
        public string MaTP { get; set; }
        public PHONGBAN(string mapb, string tenpb, string matp)
        {
            MaPB = mapb;
            TenPB = tenpb;
            MaTP = matp;
        }
    }
}
