//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    using System.Data;

    public partial class TIENLUONG
    {
        private DBConnection dbconn = new DBConnection();
        public string MaNV { get; set; }
        public string MaCV { get; set; }
        public Nullable<decimal> LuongCB { get; set; }
        public Nullable<decimal> LuongThuong { get; set; }
        public Nullable<decimal> LuongPhat { get; set; }
        public Nullable<decimal> LuongThucTe { get; set; }
        public TIENLUONG(string MaNV, string MaCV, float HeSoLuong, int LuongCoBan, int LuongThuong, int SoNgayNghi)
        {
            /* Tim he so luong */
            string sql = $"select HeSoLuong from CHUCVU where MaCV = {this.MaCV}";
            DataTable data = dbconn.FormLoad(sql);
            DataRow row = data.Rows[0];
            HeSoLuong = (float)row["HeSoLuong"];

            this.MaNV = MaNV;
            this.MaCV = MaCV;
            this.LuongCB = LuongCB;
            this.LuongThuong = LuongThuong;
            LuongPhat = (decimal)(HeSoLuong * LuongCoBan * SoNgayNghi / 30);
            LuongThucTe = (decimal)(HeSoLuong * LuongCoBan + LuongThuong) - LuongPhat;
        }
    }
}
