//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_QLCongTy
{
    using Microsoft.Office.Interop.Excel;
    using System;
    using System.Collections.Generic;
    
    public partial class TIENLUONG
    {
        public string MaNV { get; set; }
        public string MaCV { get; set; }
        public int Thang { get; set; }
        public int Nam { get; set; }
        public Nullable<decimal> LuongCB { get; set; }
        public Nullable<decimal> LuongThuong { get; set; }
        public Nullable<decimal> LuongPhat { get; set; }
        public Nullable<double> LuongThucTe { get; set; }
    
        public virtual CHUCVU CHUCVU { get; set; }
        public virtual NHANSU NHANSU { get; set; }
        public TIENLUONG()
        {
            LuongCB = 1000000;
            LuongThuong = 0;
            LuongPhat = 0;
            LuongThucTe = 0;
        }
        public TIENLUONG(string MaNV, string MaCV, int Thang, int Nam, int Luongthuong, decimal Luongphat, float Luongthucte)
        {
            this.MaNV = MaNV;
            this.MaCV = MaCV;
            this.Thang = Thang;
            this.Nam = Nam;
            LuongCB = 1000000;
            LuongThuong = Luongthuong;
            LuongPhat = Luongphat;
            LuongThucTe = Luongthucte;
        }
    }
}
