//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QLConTy_Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TRANGTHAINHANVIEN
    {
        public string MaNV { get; set; }
        public string TenNV { get; set; }
        public string TrinhDo { get; set; }
        public string TrangThai { get; set; }
        public Nullable<int> DanhGia { get; set; }
    }
}
